services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoUnifiedNewsAliases\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection,ModuleNewsHelper.php,ContaoUnifiedNewsAliasesBundle.php}
